export { default as Home } from "./Home";
export { default as Eksterijer } from "./Eksterijer";
export { default as Interijer } from "./Interijer";
export { default as Poliranje } from "./Poliranje";
export { default as Paketi } from "./Paketi";
export { default as About } from "./About";
export { default as Gallery } from "./Gallery";
export { default as Contact } from "./Contact";
export { default as Privacy } from "./Privacy";
